name: StickyTracker
author: savior67
version: Beta 1.1.0
load: POSTWORLD
main: com.aetheriumwars.stickytracker.StickyTracker
commands:
  stickytracker:
    aliases: [strack]
    description: Main Command of Sticky Tracker
    usage: /stickytracker