name: StickyTracker
author: savior67
version: R1.2.0
load: POSTWORLD
main: com.aetheriumwars.stickytracker.StickyTracker
commands:
  stickytracker:
    aliases: [strack]
    description: Main Command of Sticky Tracker
    usage: /stickytracker